
//package Calculations;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;




public class Euler2 
{
    public void distinctpowers()
    {
        /*
        Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
        2^2=4, 2^3=8, 2^4=16, 2^5=32
        3^2=9, 3^3=27, 3^4=81, 3^5=243
        4^2=16, 4^3=64, 4^4=256, 4^5=1024
        5^2=25, 5^3=125, 5^4=625, 5^5=3125
        If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
        4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
        How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
        */
        
        BigInteger d = BigInteger.valueOf(0);
        ArrayList<BigInteger> results1 = new ArrayList<>(); 
        for(int i=2;i<=100;i++)
        {
            for(int j=2;j<=100;j++)
            {
                d=BigInteger.valueOf(i).pow(j);
                results1.add(d);
            }
        }
       
            
        Collection<BigInteger> noDups = new HashSet<BigInteger>(results1);//σβηνει διπλοτυπα!!
        System.out.println(noDups.size());
        // System.out.println(noDups);// θα ειναι μη ταξινoμημενο  
        
        
        //σε περιπτωση που θελουμε κ να τα ταξινομησουμε αυτο γινεται αν τα μεταφερουμε στην αρχικη λιστα
      /*   results1.clear();
         results1.addAll(noDups);    
                                        
         
         Collections.sort(results1);   //ταξινομηση
         
          System.out.println(results1.size());
         System.out.println(results1);*/ 
        
        
              //ενναλακτικα!   διαγραφει τα διπλοτυπα απο μια λιστα Biginteger
   /*   for(int m=0;m<results1.size()-1;m++)
       {
           for(int n=m+1;n<results1.size();n++)
           {
               if(results1.get(m).equals(results1.get(n)))
               {
                   results1.remove(n);
               }
                   
           }
       }*/
        
    }
    
    public void  digit_1000_Fibonacci_number()
 {
    /*
    The Fibonacci sequence is defined by the recurrence relation:

Fn = Fn−1 + Fn−2, where F1 = 1 and F2 = 1.
Hence the first 12 terms will be:

F1 = 1
F2 = 1
F3 = 2
F4 = 3
F5 = 5
F6 = 8
F7 = 13
F8 = 21
F9 = 34
F10 = 55
F11 = 89
F12 = 144
The 12th term, F12, is the first term to contain three digits.

What is the index of the first term in the Fibonacci sequence to contain 1000 digits?*/
     ArrayList<BigInteger> fibon = new ArrayList<>();
    
     fibon.add(BigInteger.valueOf(1));
    fibon.add(BigInteger.valueOf(1));
   
    BigInteger sum;
    
    
  
        
        while(fibon.get(fibon.size() -1).toString().length()<1000)
        {    
        sum = fibon.get(fibon.size()-1).add(fibon.get(fibon.size()-2));
        fibon.add(sum);
        }
        
        
      
        
   
     System.out.println(fibon.size());
    // System.out.println(fibon);
     
     
   }  
    
    
    
}
